#!/bin/bash

npm install

git clone https://github.com/DaemonAlchemist/atp-cpp-vector.git vendor/daemonalchemist/atp-vector
git clone https://github.com/DaemonAlchemist/atp-coordinate-systems.git vendor/daemonalchemist/atp-coordinate-systems
